#!/usr/bin/env bash
FILE="${0#./fetch-}"
FILE="${FILE%.sh}"
URL="https://downloads.raspberrypi.org/$FILE"
echo "Fetching latest from $URL"
LOADED=$(curl -sLO "$URL" -C - -w '%{filename_effective}')
sha256sum "$LOADED"
unzip -u "$LOADED"
