#!/bin/bash
set -eou pipefail
SCRIPTNAME="${0##*/}"
function error() {
    echo -n "$SCRIPTNAME: ERROR occured in line $1: "
    shift
    echo "$@"
}
if (( EUID != 0 )); then
    error $LINENO "You need to be running as root."
    exit 253
fi

MYNAME="${SCRIPTNAME%.*}"
DATE=$(date -Iseconds | sed 's/:/-/g')
IMG="${1:-2020-05-27-raspios-buster-lite-armhf.img}"
BASE="${IMG%%.img}"
LOG=$MYNAME-$DATE-$BASE
{
    set -x

    options='z za Z Za'
    for run in $options; do
        time pishrink.sh -dv"$run" "$BASE".img "$BASE-$run".img
    done

    # override implicit options
    export PISHRINK_GZIP='-v1'
    export PISHRINK_XZ='-fv0T0'
    for run in $options; do
        time pishrink.sh -dv"$run" "$BASE".img "$BASE-$run"-env.img
    done

    ls -hltS "$BASE"-*.img.*
    uname -a
} &> >(tee -a "$LOG".log)
